// ==================================================
// WELLNESS NEED SELECTION
// ==================================================

const needCards =
    document.querySelectorAll(".need-card");


const exerciseSection =
    document.getElementById("exerciseSection");

const exerciseList =
    document.getElementById("exerciseList");

const exerciseTitle =
    document.getElementById("exerciseTitle");


let selectedNeed = null;


// ==================================================
// WELLNESS EXERCISES
// ==================================================

const exercises = {

    breathing: {

        icon: "🌬️",

        title: "Deep Breathing",

        description:
            "Slow your breathing and help your body settle down.",

        content: `

        <div class="breathing-exercise">

            <p class="exercise-instruction">
                Follow the circle and breathe slowly.
            </p>


            <div class="breathing-circle" id="breathingCircle">

                <span class="breathing-status" id="breathingStatus">
                    Ready
                </span>

                <strong class="breathing-count" id="breathingCount">
                    4
                </strong>

                <small>
                    seconds
                </small>

            </div>


            <p class="breathing-round" id="breathingRound">
                5 calming rounds
            </p>


            <button
                type="button"
                class="start-exercise-btn"
                id="startBreathingBtn">

                <i class="fa-solid fa-play"></i>

                Start Exercise

            </button>

        </div>

    `

    },


    grounding: {

        icon: "🧘",

        title: "5-4-3-2-1 Grounding",

        description:
            "Bring your attention back to the present moment.",

        content: `

        <div class="grounding-exercise">

            <div class="grounding-progress">

                <span id="groundingStep">
                    Step 1 of 5
                </span>

                <div class="grounding-progress-track">

                    <div
                        class="grounding-progress-bar"
                        id="groundingProgressBar">
                    </div>

                </div>

            </div>


            <div
                class="grounding-step-content"
                id="groundingStepContent">

                <!-- Generated by JavaScript -->

            </div>


            <div class="grounding-actions">

                <button
                    type="button"
                    class="grounding-btn secondary"
                    id="groundingPreviousBtn"
                    disabled>

                    <i class="fa-solid fa-arrow-left"></i>

                    Previous

                </button>


                <button
                    type="button"
                    class="grounding-btn primary"
                    id="groundingNextBtn">

                    Next

                    <i class="fa-solid fa-arrow-right"></i>

                </button>

            </div>

        </div>

    `

    },


    sleep: {

        icon: "🌙",

        title: "Sleep Relaxation",

        description:
            "Slow down and prepare your body and mind for rest."

    },


    focus: {

        icon: "🎯",

        title: "Quick Focus Reset",

        description:
            "Clear distractions and gently bring your attention back."

    },


    selfcare: {

        icon: "💙",

        title: "Self-Compassion Break",

        description:
            "Take a short pause and respond to yourself with kindness."

    },


    gratitude: {

        icon: "🙏",

        title: "Gratitude Exercise",

        description:
            "Take a moment to notice something positive in your day."

    },


    connection: {

        icon: "🤝",

        title: "Connection Reset",

        description:
            "Take one small step toward feeling more connected."

    }

};

// ==================================================
// NEED → EXERCISE MAPPING
// ==================================================

const needExercises = {

    stress: {

        title: "Stress Relief Exercises",

        exercises: [
            "breathing",
            "grounding",
            "selfcare"
        ]

    },


    relax: {

        title: "Relaxation Exercises",

        exercises: [
            "breathing",
            "gratitude",
            "grounding"
        ]

    },


    sleep: {

        title: "Better Sleep Exercises",

        exercises: [
            "sleep",
            "breathing",
            "selfcare"
        ]

    },


    focus: {

        title: "Focus Exercises",

        exercises: [
            "focus",
            "grounding",
            "breathing"
        ]

    },


    selfcare: {

        title: "Self-Care Exercises",

        exercises: [
            "selfcare",
            "gratitude",
            "breathing"
        ]

    },


    loneliness: {

        title: "Connection & Comfort Exercises",

        exercises: [
            "connection",
            "selfcare",
            "grounding"
        ]

    }

};


// ==================================================
// RENDER EXERCISES
// ==================================================

function renderExercises(need) {


    // Stop any running exercise before changing category

    stopBreathingExercise();



    const selected =
        needExercises[need];


    if (!selected) return;


    // Change heading

    exerciseTitle.textContent =
        selected.title;


    // Clear previous exercises

    exerciseList.innerHTML = "";


    // Create exercise cards

    selected.exercises.forEach((exerciseKey) => {

        const exercise =
            exercises[exerciseKey];


        const card =
            document.createElement("div");


        card.className = "exercise-card";

        card.dataset.exercise = exerciseKey;


        card.innerHTML = `

    <button
        type="button"
        class="exercise-toggle">

        <span class="exercise-icon">
            ${exercise.icon}
        </span>

        <span class="exercise-info">

            <span class="exercise-name">
                ${exercise.title}
            </span>

            <span class="exercise-description">
                ${exercise.description}
            </span>

        </span>

        <i class="fa-solid fa-chevron-down exercise-arrow"></i>

    </button>


<div class="exercise-content">

    <div class="exercise-content-inner">

        ${exercise.content
                ? exercise.content
                : `
                    <p>
                        ${exercise.description}
                    </p>

                    <span class="exercise-coming">
                        Exercise ready to begin.
                    </span>
                `
            }

    </div>

</div>

`;


        exerciseList.appendChild(card);

    });



    // ================= ACCORDION =================

    const exerciseCards =
        exerciseList.querySelectorAll(".exercise-card");


    exerciseCards.forEach((card) => {

        const toggle =
            card.querySelector(".exercise-toggle");


        toggle.addEventListener("click", () => {

            const isOpen =
                card.classList.contains("active");


            // Close all exercise cards

            exerciseCards.forEach((item) => {

                item.classList.remove("active");

            });


            // Open clicked card if it wasn't already open

            if (!isOpen) {

                card.classList.add("active");

            }

        });

    });




    // Show section

    exerciseSection.classList.add("show");


    // Setup interactive exercises

    setupBreathingExercise();

    setupGroundingExercise();


    // Smoothly move toward exercises

    setTimeout(() => {

        exerciseSection.scrollIntoView({

            behavior: "smooth",

            block: "start"

        });

    }, 100);

}


// ==================================================
// DEEP BREATHING EXERCISE
// ==================================================

let breathingRunning = false;

let breathingTimer = null;

let breathingTimeout = null;


function setupBreathingExercise() {

    const startBtn =
        document.getElementById("startBreathingBtn");

    const circle =
        document.getElementById("breathingCircle");

    const status =
        document.getElementById("breathingStatus");

    const count =
        document.getElementById("breathingCount");

    const roundText =
        document.getElementById("breathingRound");


    // Breathing exercise may not currently be rendered

    if (
        !startBtn ||
        !circle ||
        !status ||
        !count
    ) {

        return;

    }


    startBtn.addEventListener("click", () => {

        if (breathingRunning) {

            stopBreathingExercise();

            return;

        }


        breathingRunning = true;


        startBtn.innerHTML = `

            <i class="fa-solid fa-stop"></i>

            Stop Exercise

        `;


        runBreathingExercise(
            circle,
            status,
            count,
            roundText,
            startBtn
        );

    });

}


function runBreathingExercise(
    circle,
    status,
    count,
    roundText,
    startBtn
) {

    let round = 1;

    const totalRounds = 5;


    function startRound() {

        if (!breathingRunning) return;


        if (round > totalRounds) {

            completeBreathingExercise(
                circle,
                status,
                count,
                roundText,
                startBtn
            );

            return;

        }


        roundText.textContent =
            `Round ${round} of ${totalRounds}`;


        // Breathe In

        runBreathingPhase(

            circle,

            status,

            count,

            "Breathe In",

            4,

            "breathe-in",

            () => {


                // Hold

                runBreathingPhase(

                    circle,

                    status,

                    count,

                    "Hold",

                    4,

                    "hold",

                    () => {


                        // Breathe Out

                        runBreathingPhase(

                            circle,

                            status,

                            count,

                            "Breathe Out",

                            6,

                            "breathe-out",

                            () => {


                                // Rest

                                runBreathingPhase(

                                    circle,

                                    status,

                                    count,

                                    "Rest",

                                    2,

                                    "rest",

                                    () => {

                                        round++;

                                        startRound();

                                    }

                                );

                            }

                        );

                    }

                );

            }

        );

    }


    startRound();

}


function runBreathingPhase(
    circle,
    status,
    count,
    phaseName,
    seconds,
    phaseClass,
    callback
) {

    if (!breathingRunning) return;


    clearInterval(breathingTimer);

    clearTimeout(breathingTimeout);


    circle.classList.remove(
        "breathe-in",
        "hold",
        "breathe-out",
        "rest"
    );


    // Force browser to register class removal

    void circle.offsetWidth;


    circle.classList.add(phaseClass);


    status.textContent =
        phaseName;


    let remaining =
        seconds;


    count.textContent =
        remaining;


    breathingTimer = setInterval(() => {

        remaining--;


        if (remaining > 0) {

            count.textContent =
                remaining;

        }

    }, 1000);


    breathingTimeout = setTimeout(() => {

        clearInterval(breathingTimer);


        if (breathingRunning) {

            callback();

        }

    }, seconds * 1000);

}


function stopBreathingExercise() {

    breathingRunning = false;


    clearInterval(breathingTimer);

    clearTimeout(breathingTimeout);


    const circle =
        document.getElementById("breathingCircle");

    const status =
        document.getElementById("breathingStatus");

    const count =
        document.getElementById("breathingCount");

    const roundText =
        document.getElementById("breathingRound");

    const startBtn =
        document.getElementById("startBreathingBtn");


    if (circle) {

        circle.classList.remove(
            "breathe-in",
            "hold",
            "breathe-out",
            "rest"
        );

    }


    if (status) {

        status.textContent = "Ready";

    }


    if (count) {

        count.textContent = "4";

    }


    if (roundText) {

        roundText.textContent =
            "5 calming rounds";

    }


    if (startBtn) {

        startBtn.innerHTML = `

            <i class="fa-solid fa-play"></i>

            Start Exercise

        `;

    }

}


function completeBreathingExercise(
    circle,
    status,
    count,
    roundText,
    startBtn
) {

    breathingRunning = false;


    clearInterval(breathingTimer);

    clearTimeout(breathingTimeout);


    circle.classList.remove(
        "breathe-in",
        "hold",
        "breathe-out",
        "rest"
    );


    status.textContent =
        "Complete";


    count.textContent =
        "✓";


    roundText.textContent =
        "Nice work. Take a moment before moving on.";


    startBtn.innerHTML = `

        <i class="fa-solid fa-rotate-right"></i>

        Start Again

    `;

}

// ==================================================
// 5-4-3-2-1 GROUNDING EXERCISE
// ==================================================

const groundingSteps = [

    {
        number: 5,

        sense: "Things You Can See",

        instruction:
            "Look around slowly and notice five things you can see. Pay attention to colors, shapes, light, and small details."
    },

    {
        number: 4,

        sense: "Things You Can Touch",

        instruction:
            "Notice four things you can physically feel, such as your clothing, the chair beneath you, or the surface near you."
    },

    {
        number: 3,

        sense: "Things You Can Hear",

        instruction:
            "Pause and listen carefully. Notice three sounds around you, even quiet or distant ones."
    },

    {
        number: 2,

        sense: "Things You Can Smell",

        instruction:
            "Notice two scents around you. If you cannot smell anything clearly, think of two familiar scents you enjoy."
    },

    {
        number: 1,

        sense: "Thing You Can Taste",

        instruction:
            "Notice one taste in your mouth right now, or think about a familiar taste that feels comforting."
    }

];

function setupGroundingExercise() {

    const stepContent =
        document.getElementById("groundingStepContent");

    const stepLabel =
        document.getElementById("groundingStep");

    const progressBar =
        document.getElementById("groundingProgressBar");

    const previousBtn =
        document.getElementById("groundingPreviousBtn");

    const nextBtn =
        document.getElementById("groundingNextBtn");


    // Grounding may not currently be rendered

    if (
        !stepContent ||
        !stepLabel ||
        !progressBar ||
        !previousBtn ||
        !nextBtn
    ) {

        return;

    }


    let currentStep = 0;


    function renderGroundingStep() {

        const step =
            groundingSteps[currentStep];


        stepLabel.textContent =
            `Step ${currentStep + 1} of ${groundingSteps.length}`;


        progressBar.style.width =
            `${((currentStep + 1) / groundingSteps.length) * 100}%`;


        stepContent.innerHTML = `

            <span class="grounding-number">
                ${step.number}
            </span>

            <span class="grounding-sense">
                ${step.sense}
            </span>

            <p class="grounding-instruction">
                ${step.instruction}
            </p>

        `;


        previousBtn.disabled =
            currentStep === 0;


        if (
            currentStep ===
            groundingSteps.length - 1
        ) {

            nextBtn.innerHTML = `

                Complete

                <i class="fa-solid fa-check"></i>

            `;

        } else {

            nextBtn.innerHTML = `

                Next

                <i class="fa-solid fa-arrow-right"></i>

            `;

        }

    }


    renderGroundingStep();

    previousBtn.addEventListener("click", () => {

        if (currentStep > 0) {

            currentStep--;

            renderGroundingStep();

        }

    });


    nextBtn.addEventListener("click", () => {

        if (
            currentStep <
            groundingSteps.length - 1
        ) {

            currentStep++;

            renderGroundingStep();

            return;

        }


        // Exercise completed

        stepLabel.textContent =
            "Complete";


        progressBar.style.width =
            "100%";


        stepContent.innerHTML = `

            <div class="grounding-complete">

                <div class="grounding-complete-icon">

                    <i class="fa-solid fa-check"></i>

                </div>

                <h3>
                    Grounding Complete
                </h3>

                <p>
                    Take one slow breath and notice how
                    you feel before moving on.
                </p>

            </div>

        `;


        previousBtn.style.display =
            "none";


        nextBtn.innerHTML = `

            <i class="fa-solid fa-rotate-right"></i>

            Start Again

        `;


        nextBtn.onclick = () => {

            currentStep = 0;

            previousBtn.style.display = "";

            nextBtn.onclick = null;

            renderGroundingStep();

        };

    });

}









needCards.forEach((card) => {

    card.addEventListener("click", () => {


        // Remove previous selection

        needCards.forEach((item) => {

            item.classList.remove("selected");

        });


        // Select clicked card

        card.classList.add("selected");


        // Store selected need

        selectedNeed = card.dataset.need;


        // Testing

        console.log(
            "Selected Wellness Need:",
            selectedNeed
        );

        // Show recommended exercises

        renderExercises(selectedNeed);

    });

});